name: Build and Deploy
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Build Vue Project
        run: npm run build

      - name: Set up Git
        run: |
          git config --global user.email "reinkejace@gmail.com"
          git config --global user.name "jreinke428"
          git config --global credential.helper '!f() { echo "username=github-actions" ; echo "password=${{ secrets.GH_TOKEN }}" ; git credential reject ; }; f'

      - name: Create Build Branch
        run: |
          git checkout -b build
          git checkout main -- dist
          git rm -r --cached .
          mv dist/* .
          rmdir dist
          git add .
          git commit -m "Build and deploy"
          git push origin build
