name: Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-commands:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy
        run: |
          npm run build
          git add dist && git commit -m 'build dist'
          git subtree push --prefix dist origin build
